### PR TITLE
Alert window during registration

### PR DESCRIPTION
**Pull request by JanOppolzer**
When no metadata are pasted into <textarea> during a registration, the
user is informed about the need to manually fill in all the information.

### CODE REVIEW

**Comment by janul** [comment]
tanks for it. can u pls make this change in locals-v7.js instead

**Comment by JanOppolzer** [comment]
Sure, give me a minute.

**Comment by JanOppolzer** [comment]
Done.

**Comment by JanOppolzer** [comment]
Oh, I accidentally closed the pull request yesterday...

**Pull request merged**
